name: Publish vault

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  publish:
    uses: tjakobsson/brain-manual/.github/workflows/publish-pages.yml@3c21593ca9ca98c20988ba462271832588e521da
    with:
      vault: .
